selected_dataset: mcity_fisheye_2000  # Choose from datasets.yaml
v51_embedding_models: # Choose from Embedding models https://docs.voxel51.com/user_guide/model_zoo/models.html
  - clip-vit-base32-torch
  - open-clip-torch
  - dinov2-vitl14-torch
  - mobilenet-v2-imagenet-torch
  - resnet152-imagenet-torch
  - vgg19-imagenet-torch
  - zero-shot-detection-transformer-torch
num_workers: !!int 8