FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime
RUN apt-get update && \
    apt-get install -y \
    git \
    libgl1 \
    libglib2.0-0 \
    libcurl4

ENV RUNNING_IN_DOCKER=true

WORKDIR /launch

COPY --link requirements.txt ./
RUN pip install -r requirements.txt

# Copy the entire repository
COPY --link . ./
ENTRYPOINT ["python", "main.py"]