AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mcity data engine deployment'

Parameters:
  OPENAIAPIKEY:
    Type: String
    Default: sk-123456789123456789123456789 # Replace this key
    NoEcho: true
  KeyPairName:
    Type: String
    Default: mcity-data-engine-key
    Description: The name of the new Key Pair to be created
  RepoURL:
    Type: String
    Default: 'https://github.com/mcity/mcity_data_engine.git'
    Description: URL of the public git repository
  InstanceType:
    Type: String
    Default: r5.large
  HFTOKEN:
    Type: String
    Default: hf_asdasdasduasdasdasTSDSDasfadfasdasd
    NoEcho: true

Resources:
  MyKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: !Ref KeyPairName

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5225
          ToPort: 5225
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8002
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5151
          ToPort: 5151
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref MyKeyPair
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      ImageId: ami-0722d33f9d127fc05
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          cd /home/ubuntu/myapp

          python3 -m venv venv
          source venv/bin/activate

          cat <<EOF > .env
          LLM_PROVIDER=openai
          #OPENAI_MODEL=gpt-5-mini
          OPENAI_API_KEY=${OPENAIAPIKEY}
          HF_TOKEN=${HFTOKEN}
          EOF

          chmod 600 .env

          # PYTHONPATH lets mcp_layer scripts import the config/ package from project root
          export PYTHONPATH=/home/ubuntu/myapp

          nohup python3 session_v51.py > session_v51.log 2>&1 &

          cd mcp_layer
          nohup python3 client_chat.py --ui > client_chat.log 2>&1 &
          nohup python3 mcp_server.py > mcp_server.log 2>&1  &
          nohup python3 llm_clients.py > llm_clients.log 2>&1  &
          nohup python3 chat_server.py > chat_server.log 2>&1   &
          nohup uvicorn ingest_server:app --host 0.0.0.0 --port 8002 --reload > ingest_server.log 2>&1


Outputs:
  PublicIP:
    Description: Instance Public IP
    Value: !GetAtt WebServerInstance.PublicIp
  KeyPairID:
    Description: ID of the key pair for retrieving the private key
    Value: !GetAtt MyKeyPair.KeyPairId
