datasets:
  - name: mcity_fisheye_2000
    loader_fct: load_mcity_fisheye_2000
    hf_dataset_name: mcity-data-engine/mcity_fisheye_v51
    local_path: datasets/midadvrb_2000/
    v51_type: YOLOv5Dataset
    v51_splits: ["train", "val"]
  - name: mcity_fisheye_2100
    loader_fct: load_dataset_from_hf_hub
    hf_dataset_name: mcity-data-engine/mcity-fisheye-vru-2844
  - name: mcity_fisheye_2000_vru_only
    loader_fct: load_dataset_from_hf_hub
    hf_dataset_name: danielbogdoll/mcity_fisheye_2000_vru_only
  - name: mcity_fisheye_2100_vru_only
    loader_fct: load_dataset_from_hf_hub
    hf_dataset_name: danielbogdoll/mcity_fisheye_2100_vru_only
  - name: mcity_fisheye_3_months
    loader_fct: load_mcity_fisheye_3_months
    local_path: datasets/midadvrb_3_months/
    v51_type: YOLOv5Dataset
    v51_splits: ["train", "val"]
  - name: fisheye8k
    loader_fct: load_fisheye_8k
    hf_dataset_name: Voxel51/fisheye8k
  - name: mcity_fisheye_ano_ped
    loader_fct: load_mcity_fisheye_2000
    local_path: datasets/midadvrb_ano_ped/
    v51_type: YOLOv5Dataset
    v51_splits: ["train", "val"]
    anomalib_masks_path: datasets/midadvrb_ano_ped_masks/
  - name: mars_multitraversal
    loader_fct: load_mars_multitraversal
    local_path: datasets/MARS/Multitraversal_2023_10_04-2024_03_08/
    hf_dataset_name: ai4ce/MARS
    hf_path: Multitraversal_2023_10_04-2024_03_08
  - name: mars_multiagent
    loader_fct: load_mars_multiagent
    local_path: Multiagent_53scene
    hf_dataset_name: ai4ce/MARS
    hf_path: datasets/MARS/Multiagent_53scene/
    v51_config: mars_multiagent.yaml
  - name: annarbor_rolling
    loader_fct: load_annarbor_rolling
    local_path: datasets/dataengine_rolling/1/decoded
    v51_type: FiftyOneDataset
  - name: SUNRGBD
    loader_fct: load_sunrgbd
    local_path: /home/wizard/mcity_data_engine/SUNRGBD
    v51_type: FiftyOneDataset
