# Usage:
# docker compose up --remove-orphans codetr_train/slurm_train/test
# docker compose up -d --remove-orphans codetr_dev

x-common-configuration: &common-configuration
  image: codetr
  volumes:
    - /home/dbogdoll/mcity_data_engine/custom_models/CoDETR/Co-DETR:/launch
    - /media/dbogdoll/Datasets:/media/dbogdoll/Datasets:rw
    - /home/dbogdoll/mcity_data_engine/output/docker:/launch/output:rw
  environment:
    - PYTHONPATH=/launch
  deploy:
    resources:
      limits:
        cpus: '24'
        memory: 48g
      reservations:
        devices:
          - capabilities: [ gpu ]
  shm_size: '32g'
  memswap_limit: '56g'

services:
  # Service for training using dist_train.sh script
  codetr_train:
    <<: *common-configuration
    container_name: codetr_train
    entrypoint: [ "/usr/local/bin/entrypoint_compose.sh" ]
    command: sh tools/dist_train.sh projects/configs/co_deformable_detr/co_deformable_detr_r50_1x_coco.py 1 path_to_exp

  # Service for training using slurm_train.sh script
  codetr_slurm_train:
    <<: *common-configuration
    container_name: codetr_slurm_train
    entrypoint: [ "/usr/local/bin/entrypoint_compose.sh" ]
    command: sh tools/slurm_train.sh partition job_name projects/configs/co_deformable_detr/co_deformable_detr_r50_1x_coco.py path_to_exp

  # Service for testing using dist_test.sh script
  codetr_test:
    <<: *common-configuration
    container_name: codetr_test
    entrypoint: [ "/usr/local/bin/entrypoint_compose.sh" ]
    command: sh tools/dist_test.sh projects/configs/co_deformable_detr/co_deformable_detr_r50_1x_coco.py path_to_checkpoint 1 --eval bbox

  # Service for interactive development session
  codetr_dev:
    <<: *common-configuration
    container_name: codetr_dev
    tty: true
    stdin_open: true
    entrypoint: [ "/bin/bash" ]
