name: Lighthouse Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest  # The host runner
    container:
      image: dbogdollresearch/data_engine_lighthouse:latest  # Imitate Lighthouse setup

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python 3.11.5
      run: |
        python3.11 -m venv venv
        source venv/bin/activate

    - name: Upgrade pip
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi